branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git:
  depth: 3
env:
- API_SERVER=https://easy-mock.com/mock/5d54f55db802294dc3f888f5 PUBLIC_PATH=https://liangsfs163.github.io/nuxt-element-dashboard-demo/
install:
- yarn --frozen-lockfile
script:
- ./build.sh
after_success:
- GREN_GITHUB_TOKEN=$GITHUB_TOKEN yarn release
- sleep 3 && ./notify.sh
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  github-token: $GITHUB_TOKEN